#!/bin/bash
GITTOP=`git rev-parse --show-toplevel`

[ ! -d "$GITTOP/node_modules" ] && npm install

PROJ=$1
CLUS="google-waste-management-gke"
#ZONE="us-central1"     # Regional
ZONE="us-central1-c"  # Zonal

# This will create the cluster for google demos without using the GUI.
gcloud container --project $PROJ          \
            clusters create $CLUS              \
            --zone $ZONE                       \
            --username "admin"                 \
            --cluster-version "1.9.7-gke.6"   \
            --machine-type "n1-standard-2"     \
            --image-type "COS"                 \
            --disk-size "100"                  \
            --node-labels my-gke-ver=v2        \
            --scopes "https://www.googleapis.com/auth/compute","https://www.googleapis.com/auth/devstorage.read_only","https://www.googleapis.com/auth/logging.write","https://www.googleapis.com/auth/monitoring","https://www.googleapis.com/auth/servicecontrol","https://www.googleapis.com/auth/service.management.readonly","https://www.googleapis.com/auth/trace.append" \
            --num-nodes "1"                    \
            --network "default"                \
            --enable-cloud-logging             \
            --enable-cloud-monitoring          \
            --subnetwork "default"             \
            --enable-autoscaling               \
            --min-nodes "1"                    \
            --max-nodes "6"                    \
            --addons HorizontalPodAutoscaling,HttpLoadBalancing,KubernetesDashboard \
            --enable-autorepair

if [ $? != 0 ];
then
  cat<<CLUERR

  ***WARNING: failed to create the cluster, perhaps it already exists?
     Cluster: $CLUS
     Project: $PROJ
        Zone: $ZONE

CLUERR
fi
