#!/bin/bash
GITTOP=`git rev-parse --show-toplevel`
SECRETS="$GITTOP/scripts/platform-secrets"
GKE_PROJ=$1

GOOGLE_APPLICATION_CREDENTIALS=$(ls $SECRETS/*.json| head -1)
if [ -z "$GOOGLE_APPLICATION_CREDENTIALS" ];
then
  cat<<KEYERR
  ***WARNING: Application Credentials .json file not found       
KEYERR
exit 1
fi

FRONTEND_ENV="$SECRETS/frontend-env"

# download fb data and write to json
mkdir $SECRETS/temp
firebase setup:web --project $GKE_PROJ -j > $SECRETS/temp/fbconfig.json

# add result to frontend-env
node $GITTOP/scripts/fbimport.js $SECRETS

kubectl create secret generic application-credentials --from-file=key.json=$GOOGLE_APPLICATION_CREDENTIALS
kubectl create secret generic frontend-env --from-file=env.js=$FRONTEND_ENV
